export const LAY_DANH_SACH_KHOA_HOC_REQUEST = "LAY_DANH_SACH_KHOA_HOC_REQUEST";
export const LAY_DANH_SACH_KHOA_HOC_SUCCESS = "LAY_DANH_SACH_KHOA_HOC_SUCCESS";
export const LAY_DANH_SACH_KHOA_HOC_FAIL = "LAY_DANH_SACH_KHOA_HOC_FAIL";