export const GET_COURSE_DETAIL_SUCCESS = "GET_COURSE_DETAIL_SUCCESS";
export const GET_COURSE_DETAIL_FAIL = "GET_COURSE_DETAIL_FAIL";

export const DANG_KY_KHOA_HOC_THANH_CONG ="DANG_KY_KHOA_HOC_THANH_CONG";
export const DANG_KY_KHOA_HOC_THAT_BAI = "DANG_KY_KHOA_HOC_THAT_BAI"