export const GET_COURSE_BY_CATALOG_REQUEST = "GET_COURSE_BY_CATALOG_REQUEST";
export const GET_COURSE_BY_CATALOG_SUCCESS = "GET_COURSE_BY_CATALOG_SUCCESS";
export const GET_COURSE_BY_CATALOG_FAIL = "GET_COURSE_BY_CATALOG_FAIL";
